name: Model Serving Pipeline

on:
  push:
    paths:
      - 'model_serving/**/*'
  pull_request:
    paths:
      - 'model_serving/**/*'
  workflow_dispatch:
    # Allows you to trigger this workflow manually from the GitHub Actions tab
  repository_dispatch:
    types: [model-trained]  # Custom event type

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  azure-build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build model_serving -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/mlopstextclassification_model_serving:${{ github.sha }} --build-arg MLFLOW_DATABRICKS_URL=${{ secrets.MLFLOW_DATABRICKS_URL }} --build-arg MLFLOW_DATABRICKS_TOKEN=${{ secrets.MLFLOW_DATABRICKS_TOKEN }} -f model_serving/Dockerfile
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mlopstextclassification_model_serving:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/mlopstextclassification_model_serving:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: mlopstextclassification-master
          ports: '8501'
          location: 'west us'
